### ISSUE TITLE
missing dep Term::Choose::LineFold

### ISSUE THREAD

**Issue by stepht** [kuerbis/Term-Choose-Util#2]
cannot build on cygwin....
hth

Checking if you have Encode::Locale 0 ... Yes (1.05)
Checking if you have Term::Choose::LineFold 1.500 ... No
Checking if you have File::Basename 0 ... Yes (2.85)
Checking if you have List::Util 0 ... Yes (1.43)
==> Found dependencies: Term::Choose::LineFold
Searching Term::Choose::LineFold (1.500) on cpanmetadb ...
! Finding Term::Choose::LineFold on cpanmetadb failed.
Searching Term::Choose::LineFold (1.500) on metacpan ...
! Could not find a release matching Term::Choose::LineFold (1.500) on MetaCPAN.
Searching Term::Choose::LineFold on mirror http://www.cpan.org ...
Downloading index file http://www.cpan.org/modules/02packages.details.txt.gz ...
Uncompressing index file...
! Finding Term::Choose::LineFold (1.500) on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution Term::Choose::LineFold (1.500)
! Installing the dependencies failed: Missing version info for module 'Term::Choose::LineFold'
! Bailing out the installation for Term-Choose-Util-0.050.

**Comment by kuerbis** [comment]
Hi, have you installed Term::Choose? Term::Choose::LineFold is part of the Term::Choose distribution. Term::Choose itself is also required by Term::Choose::Util.

**Comment by stepht** [comment]
I had previous versions, including App-DBBrowser. Somehow I could not update using cpanm. Maybe an index problem.
metacpan could not find Term::Choose::LineFold either. CPAN::Shell did not find it either.

I just reinstalled Term-Choose. But I cannot install T-C-Util.
% stephan@armen (/xddxc) %
% /pb/pmm0 Term::Choose Term::Choose::LineFold

> > cpan modus operandi: [module (-m)]
> > List: [Term::Choose] [Term::Choose::LineFold]

---CPAN--- (m)
Reading '/home/stephan/.cpan/Metadata'
  Database was generated on Sat, 27 Feb 2016 20:53:33 GMT
Module id = Term::Choose
    CPAN_USERID  KUERBIS (Matthaeus Kiem cuer2s@gmail.com)
    CPAN_VERSION 1.501
    CPAN_FILE    K/KU/KUERBIS/Term-Choose-1.501.tar.gz
    MANPAGE      Term::Choose - Choose items from a list interactively.
    INST_FILE    /opt/perl5163/lib/site_perl/5.16.3/Term/Choose.pm
    INST_VERSION 1.501

No objects of type Module found for argument Term::Choose::LineFold

% stephan@armen (/xddxc) %
% /p201b/perl -MTerm::Choose -we 'print Term::Choose->VERSION'
1.501

thanks for the quick answer. I'll have a closer look later tonight Western Europe Time.

**Comment by stepht** [comment]
Was able to install everything manually through cpanm --look. seems a cpanm thing. sorry for the noise.
cheers

**Comment by stepht** [comment]
Hi again,
I think I know what happens: if you hide a module from PAUSE then you cannot use it as a dependency.

top of LineFold.pm:
package # hide from PAUSE
Term::Choose::LineFold;

now Makefile.pm from Term-Choose-Util requires LineFold.pm
requires:
  Encode: '0'
  Encode::Locale: '0'
  Exporter: '0'
  File::Basename: '0'
  File::HomeDir: '0'
  File::Spec::Functions: '0'
  List::Util: '0'
  Term::Choose: '1.500'
  Term::Choose::LineFold: '1.500'

hth

**Comment by kuerbis** [comment]
Thx, I'll fix that.
